// lib/ai/model-manager.ts
// ONNX Runtime model manager.
// Phase 1.4: proof-of-concept that `onnxruntime-react-native` loads a bundled `.onnx`
// model and runs inference on-device, BEFORE any training-pipeline investment.
// Real progression/recovery models (Phase 1 / 4) will reuse this loader.

import { Asset } from 'expo-asset';
import { Platform } from 'react-native';

// Lazy require — onnxruntime-react-native is a native module (absent in Expo Go and on web).
let ort: typeof import('onnxruntime-react-native') | null = null;
function getOrt() {
  if (Platform.OS === 'web') return null; // web would need the separate onnxruntime-web package
  if (!ort) ort = require('onnxruntime-react-native');
  return ort;
}

export const PROGRESSION_FEATURE_DIM = 15;

// Throwaway POC model: input float32[1,15] -> output float32[1,1] == sum(input).
// Generated by scripts/make_dummy_onnx.py. Replaced by a trained progression_v1.onnx in Phase 1.
const DUMMY_MODEL = require('@/assets/models/dummy_progression.onnx');

let sessionPromise: Promise<any> | null = null;

async function resolveModelPath(assetModule: number): Promise<string> {
  const asset = Asset.fromModule(assetModule);
  if (!asset.downloaded) {
    await asset.downloadAsync();
  }
  const uri = asset.localUri ?? asset.uri;
  if (!uri) throw new Error('Could not resolve ONNX asset localUri');
  // onnxruntime-react-native wants a bare filesystem path on iOS (no file:// scheme).
  // NOTE — iOS standalone builds (microsoft/onnxruntime #26738 / #27062): loading straight
  // from the app bundle can fail in production. The fix is to copy the model into a writable
  // dir (expo-file-system documentDirectory) before create(). The dev-client POC loads fine
  // from localUri, so that hardening is deferred to standalone packaging (Phase 8).
  return uri.startsWith('file://') ? uri.replace('file://', '') : uri;
}

async function getSession() {
  const o = getOrt();
  if (!o) throw new Error(`ONNX Runtime is not available on platform "${Platform.OS}".`);
  if (!sessionPromise) {
    sessionPromise = resolveModelPath(DUMMY_MODEL).then((path) => o.InferenceSession.create(path));
  }
  return sessionPromise;
}

export type OnnxPocResult = {
  ok: boolean;
  message: string;
  inputName?: string;
  outputName?: string;
  output?: number[];
  expectedSum?: number;
  latencyMs?: number;
};

// Phase 1.4 proof-of-concept: load the dummy model and run one inference, asserting the
// output equals the sum of the inputs (proves real on-device computation, not just a session open).
export async function testOnnxRuntime(): Promise<OnnxPocResult> {
  const o = getOrt();
  if (!o) {
    return {
      ok: false,
      message: `ONNX Runtime unavailable on "${Platform.OS}" — run a dev client on iOS/Android.`,
    };
  }
  try {
    const session = await getSession();
    const inputName = session.inputNames[0];
    const outputName = session.outputNames[0];

    const values = Array.from({ length: PROGRESSION_FEATURE_DIM }, (_, i) => i + 1); // 1..15
    const expectedSum = values.reduce((a, b) => a + b, 0); // 120
    const tensor = new o.Tensor('float32', Float32Array.from(values), [1, PROGRESSION_FEATURE_DIM]);

    const t0 = Date.now();
    const results = await session.run({ [inputName]: tensor });
    const latencyMs = Date.now() - t0;

    const output = Array.from(results[outputName].data as Float32Array);
    const matches = output.length > 0 && Math.abs(output[0] - expectedSum) < 1e-3;

    return {
      ok: matches,
      message: matches
        ? `Inference OK — output ${output[0]} = sum ${expectedSum}, ${latencyMs}ms`
        : `Ran, but output ${output[0]} != expected ${expectedSum}`,
      inputName,
      outputName,
      output,
      expectedSum,
      latencyMs,
    };
  } catch (e: any) {
    return { ok: false, message: `ONNX test failed: ${e?.message ?? e}` };
  }
}
