// lib/ai/model-manager.ts
// ONNX Runtime model manager.
// Phase 1.4: proof-of-concept that `onnxruntime-react-native` loads a bundled `.onnx`
// model and runs inference on-device, BEFORE any training-pipeline investment.
// Real progression/recovery models (Phase 1 / 4) will reuse this loader.

import { Asset } from 'expo-asset';
import { Platform } from 'react-native';

// Lazy require — onnxruntime-react-native is a native module (absent in Expo Go and on web).
let ort: typeof import('onnxruntime-react-native') | null = null;
function getOrt() {
  if (Platform.OS === 'web') return null; // web would need the separate onnxruntime-web package
  if (!ort) ort = require('onnxruntime-react-native');
  return ort;
}

export const PROGRESSION_FEATURE_DIM = 15;

// Throwaway POC model: input float32[1,15] -> output float32[1,1] == sum(input).
// Generated by scripts/make_dummy_onnx.py. Kept as a minimal-op runtime smoke test.
const DUMMY_MODEL = require('@/assets/models/dummy_progression.onnx');

// Trained progression classifier (Phase 1.2): 15-dim input -> [label, probabilities[3]].
const PROGRESSION_MODEL = require('@/assets/models/progression_v1.onnx');
// Class order MUST match train_model.py ACTIONS and the export's probability-index order.
export const PROGRESSION_CLASSES = ['INCREASE', 'HOLD', 'RESET'] as const;
export type ProgressionAction = (typeof PROGRESSION_CLASSES)[number];

let sessionPromise: Promise<any> | null = null;

async function resolveModelPath(assetModule: number): Promise<string> {
  const asset = Asset.fromModule(assetModule);
  if (!asset.downloaded) {
    await asset.downloadAsync();
  }
  const uri = asset.localUri ?? asset.uri;
  if (!uri) throw new Error('Could not resolve ONNX asset localUri');
  // onnxruntime-react-native wants a bare filesystem path on iOS (no file:// scheme).
  // NOTE — iOS standalone builds (microsoft/onnxruntime #26738 / #27062): loading straight
  // from the app bundle can fail in production. The fix is to copy the model into a writable
  // dir (expo-file-system documentDirectory) before create(). The dev-client POC loads fine
  // from localUri, so that hardening is deferred to standalone packaging (Phase 8).
  return uri.startsWith('file://') ? uri.replace('file://', '') : uri;
}

async function getSession() {
  const o = getOrt();
  if (!o) throw new Error(`ONNX Runtime is not available on platform "${Platform.OS}".`);
  if (!sessionPromise) {
    sessionPromise = resolveModelPath(DUMMY_MODEL).then((path) => o.InferenceSession.create(path));
  }
  return sessionPromise;
}

export type OnnxPocResult = {
  ok: boolean;
  message: string;
  inputName?: string;
  outputName?: string;
  output?: number[];
  expectedSum?: number;
  latencyMs?: number;
};

// Phase 1.4 proof-of-concept: load the dummy model and run one inference, asserting the
// output equals the sum of the inputs (proves real on-device computation, not just a session open).
export async function testOnnxRuntime(): Promise<OnnxPocResult> {
  const o = getOrt();
  if (!o) {
    return {
      ok: false,
      message: `ONNX Runtime unavailable on "${Platform.OS}" — run a dev client on iOS/Android.`,
    };
  }
  try {
    const session = await getSession();
    const inputName = session.inputNames[0];
    const outputName = session.outputNames[0];

    const values = Array.from({ length: PROGRESSION_FEATURE_DIM }, (_, i) => i + 1); // 1..15
    const expectedSum = values.reduce((a, b) => a + b, 0); // 120
    const tensor = new o.Tensor('float32', Float32Array.from(values), [1, PROGRESSION_FEATURE_DIM]);

    const t0 = Date.now();
    const results = await session.run({ [inputName]: tensor });
    const latencyMs = Date.now() - t0;

    const output = Array.from(results[outputName].data as Float32Array);
    const matches = output.length > 0 && Math.abs(output[0] - expectedSum) < 1e-3;

    return {
      ok: matches,
      message: matches
        ? `Inference OK — output ${output[0]} = sum ${expectedSum}, ${latencyMs}ms`
        : `Ran, but output ${output[0]} != expected ${expectedSum}`,
      inputName,
      outputName,
      output,
      expectedSum,
      latencyMs,
    };
  } catch (e: any) {
    return { ok: false, message: `ONNX test failed: ${e?.message ?? e}` };
  }
}

// =============================================================================
// Progression model inference (Phase 1.2 model; wired Phase 1.6)
// =============================================================================

let progressionSessionPromise: Promise<any> | null = null;

async function getProgressionSession() {
  const o = getOrt();
  if (!o) throw new Error(`ONNX Runtime is not available on platform "${Platform.OS}".`);
  if (!progressionSessionPromise) {
    progressionSessionPromise = resolveModelPath(PROGRESSION_MODEL).then((path) =>
      o.InferenceSession.create(path),
    );
  }
  return progressionSessionPromise;
}

export type ProgressionInferenceResult = {
  action: ProgressionAction;
  confidence: number;                              // max class probability
  probabilities: Record<ProgressionAction, number>;
  latencyMs: number;
};

/**
 * Run the trained progression classifier on an ordered 15-feature vector. The order MUST
 * match ProgressionFeatureVector / train_model.py FEATURE_COLS. Returns the predicted
 * action + class probabilities. Weight delta is computed deterministically downstream
 * (fixed-increment engine), not by the model.
 */
export async function runProgressionInference(features: number[]): Promise<ProgressionInferenceResult> {
  const o = getOrt();
  if (!o) throw new Error(`ONNX Runtime is not available on platform "${Platform.OS}".`);
  if (features.length !== PROGRESSION_FEATURE_DIM) {
    throw new Error(`Expected ${PROGRESSION_FEATURE_DIM} features, got ${features.length}.`);
  }
  const session = await getProgressionSession();
  const inputName = session.inputNames[0];
  const tensor = new o.Tensor('float32', Float32Array.from(features), [1, PROGRESSION_FEATURE_DIM]);

  const t0 = Date.now();
  const results = await session.run({ [inputName]: tensor });
  const latencyMs = Date.now() - t0;

  // probabilities output is float32[1,3] in PROGRESSION_CLASSES order (no ZipMap)
  const probName = 'probabilities' in results
    ? 'probabilities'
    : (session.outputNames.find((n: string) => n !== 'label') ?? session.outputNames[0]);
  const probs = Array.from(results[probName].data as Float32Array);

  let best = 0;
  for (let i = 1; i < probs.length; i++) if (probs[i] > probs[best]) best = i;

  return {
    action: PROGRESSION_CLASSES[best],
    confidence: probs[best] ?? 0,
    probabilities: { INCREASE: probs[0] ?? 0, HOLD: probs[1] ?? 0, RESET: probs[2] ?? 0 },
    latencyMs,
  };
}

// Phase 1.6 on-device check: run the real TreeEnsemble model on a sample "hit ceiling,
// low RPE, no stall" state (expect INCREASE). Confirms ORT-RN supports the ai.onnx.ml op.
export async function testProgressionModel(): Promise<OnnxPocResult> {
  const o = getOrt();
  if (!o) {
    return { ok: false, message: `ONNX Runtime unavailable on "${Platform.OS}" — run a dev client on iOS/Android.` };
  }
  try {
    // [wt, reps, rpe, sets, repMin, repMax, jump, stall, ceiling, prevWt, prevReps, prevRpe, daysSince, volTrend, recovery]
    const sample = [185, 12, 8, 3, 8, 12, 5, 0, 12, 180, 12, 8, 3, 0.5, 80];
    const r = await runProgressionInference(sample);
    const pct = (x: number) => `${Math.round(x * 100)}%`;
    return {
      ok: true,
      message:
        `Progression model OK — predicts ${r.action} ` +
        `(INC ${pct(r.probabilities.INCREASE)} / HOLD ${pct(r.probabilities.HOLD)} / RESET ${pct(r.probabilities.RESET)}), ${r.latencyMs}ms`,
    };
  } catch (e: any) {
    return { ok: false, message: `Progression model failed: ${e?.message ?? e}` };
  }
}
